# Generated by Django 5.2.10 on 2026-01-26 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='motif',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='heure',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date',
            field=models.DateField(),
        ),
    ]
