# Generated by Django 5.2.10 on 2026-01-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_medecin_email_medecin_prenom'),
        ('patients', '0004_patient_age'),
        ('rendezvous', '0002_remove_rendezvous_motif_rendezvous_heure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='date',
            new_name='date_rendezvous',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='heure',
            new_name='heure_rendezvous',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_medecin', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_patient', to='patients.patient'),
        ),
    ]
