# Generated by Django 5.2.10 on 2026-01-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_medecin_email_medecin_prenom'),
        ('patients', '0004_patient_age'),
        ('rendezvous', '0003_rename_date_rendezvous_date_rendezvous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='heure_rendezvous',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient'),
        ),
    ]
