# Generated by Django 5.2.10 on 2026-01-28 15:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_heure_consultation_motif_and_more'),
        ('medecins', '0002_medecin_email_medecin_prenom'),
        ('patients', '0004_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='date',
            new_name='date_consultation',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_medecin', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_patient', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendezvous', models.DateField()),
                ('heure_rendezvous', models.TimeField(default=datetime.time(9, 0))),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
