# Generated by Django 5.2.10 on 2026-01-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_date_consultation_date_consultation_and_more'),
        ('medecins', '0002_medecin_email_medecin_prenom'),
        ('patients', '0004_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='heure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medecins.medecin'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='RendezVous',
        ),
    ]
