# Generated by Django 5.2.10 on 2026-01-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
    ]
